---
- name: Clone polybar scripts
  git: repo='https://github.com/inomoz/polybar-scripts' dest=/home/{{ user.name }}/polybar-scripts accept_hostkey=yes update=no
  become: yes
  become_user: "{{ user.name }}"
  
- name: Install dotfiles
  ansible.builtin.shell: config-initialize.sh >> /tmp/config-initialize.log
  args:
    executable: /bin/bash
