---
- name: Clone polybar scripts
  git: repo='https://github.com/inomoz/polybar-scripts' dest=/home/{{ user.name }}/scripts/polybar-scripts accept_hostkey=yes update=no
  become: yes
  become_user: "{{ user.name }}"
  
- name: Install dotfiles
  ansible.builtin.shell: |
    #!/bin/bash
    git init --bare $HOME/.projects
    alias config='/usr/bin/git --git-dir=$HOME/.projects/ --work-tree=$HOME'
    config config --local status.showUntrackedFiles no
    echo "alias config='/usr/bin/git --git-dir=$HOME/.projects/ --work-tree=$HOME'" >> $HOME/.bashrc
  args:
    executable: /bin/bash
  delegate_to: localhost
