---
- name: Clone polybar scripts
  git: repo='https://github.com/inomoz/polybar-scripts' dest=/home/{{ user.name }}/scripts/polybar-scripts accept_hostkey=yes update=no
  become: yes
  become_user: "{{ user.name }}"
  
- name: Install dotfiles
  ansible.builtin.shell: |
    yadm clone git@github.com:inomoz/dotfiles.git
  args:
    executable: /bin/bash
  delegate_to: localhost
  become: yes
  become_user: "{{ user.name }}"
