---
- name: Clone polybar scripts
  git: repo='https://github.com/inomoz/polybar-scripts' dest=/home/{{ user.name }}/scripts/polybar-scripts accept_hostkey=yes update=no
  become: yes
  become_user: "{{ user.name }}"
  
- name: Install dotfiles
  ansible.builtin.shell: |
    git clone --bare https://github.com/inomoz/dotfiles $HOME/.dotfiles
    function config {
       /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
    }
    mkdir -p .config-backup
    config checkout
    if [ $? = 0 ]; then
      echo "Checked out config.";
      else
        echo "Backing up pre-existing dot files.";
        config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
    fi;
    config checkout
    config config status.showUntrackedFiles no
  args:
    executable: /bin/bash
  delegate_to: localhost
  become: yes
  become_user: "{{ user.name }}"
