---
- name: Install Atril
  pacman:
    name:
      - atril
    state: present
  tags:
    - atril

- name: Set Atril as default PDF viewer
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    regexp: "^application/pdf"
    state: present
    line: "application/pdf=atril.desktop"
  tags:
    - atril

- name: Jail Atril
  file:
    src: /usr/bin/firejail
    dest: /usr/bin/atril
    state: link
  tags:
    - atril
    - firejail


- name: Install pdfgrep
  pacman:
    name: pdfgrep
    state: present
  tags:
    - pdfgrep

- name: Install OCRmyPDF and dependencies
  aur:
    name:
      - python-humanfriendly
      - python-coloredlogs
      - ocrmypdf
    user: "{{ user.name }}"
  tags:
    - ocrmypdf
    - aur

- name: Install tesseract-data-eng
  pacman:
    name: tesseract-data-eng
    state: present
  tags:
    - ocrmypdf
