---
- name: Install Okular
  pacman:
    name:
      - okular
    state: present
  tags:
    - okular

- name: Set Atril as default PDF viewer
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    regexp: "^application/pdf"
    state: present
    line: "application/pdf=okular.desktop"
  tags:
    - okular

- name: Install pdfgrep
  pacman:
    name: pdfgrep
    state: present
  tags:
    - pdfgrep

- name: Install OCRmyPDF and dependencies
  aur:
    name:
      - python-humanfriendly
      - python-coloredlogs
      - ocrmypdf
    user: "{{ user.name }}"
  tags:
    - ocrmypdf
    - aur

- name: Install tesseract-data-eng
  pacman:
    name:
      - tesseract-data-eng
      - tesseract-data-rus
    state: present
  tags:
    - ocrmypdf
