---
- name: Install hunspell
  pacman:
    name:
      - hunspell
      - hunspell-en_US
    state: present
  tags:
    - hunspell

- name: Install aspell
  pacman:
    name:
      - aspell
      - aspell-en
      - aspell-ru
    state: present
  tags:
    - aspell
